✨ feat: use rootfs.prefixdir
RT-Thread/userapps pull request #41
Opened 2023-10-11 08:05 UTC by xqyjlj

添加自定义rootfs的字段

2023-10-17 05:13 UTC, BernardXiong requested changes

2023-10-17 05:13 UTC, BernardXiong commented on tools/scripts/tasks/smart-rootfs/on_run.lua
> -    create_dir(path.join(rootfs, "services"))
还是使用services呀，为什么需要更改目录名称

2023-10-17 05:13 UTC, BernardXiong commented on tools/scripts/tasks/smart-rootfs/on_run.lua
> +    create_dir(path.join(rootfs, "run"))
`/run`是用于？

2023-10-17 05:57 UTC, xqyjlj commented on tools/scripts/tasks/smart-rootfs/on_run.lua
> -    create_dir(path.join(rootfs, "services"))
linux上叫srv，之前smart由于路径和linux不一致，导致rootfs总是缺斤少两，这次想改成一样的

2023-10-17 05:58 UTC, xqyjlj commented on tools/scripts/tasks/smart-rootfs/on_run.lua
> +    create_dir(path.join(rootfs, "run"))
是一个临时文件系统，存储系统启动以来的信息。当系统重启时，这个目录下的文件应该被删掉或清除。如果有 /var/run 目录，应该让它指向 run。

2023-10-18 00:29 UTC, BernardXiong commented on tools/scripts/tasks/smart-rootfs/on_run.lua
> -    create_dir(path.join(rootfs, "services"))
也不是说smart上需要和linux保持一致

2023-10-18 02:05 UTC, xqyjlj commented on tools/scripts/tasks/smart-rootfs/on_run.lua
> -    create_dir(path.join(rootfs, "services"))
已

2023-10-18 03:03 UTC, BernardXiong approved these changes

2023-10-18 03:03 UTC, BernardXiong commented
等ci都通过合并

2023-10-18 08:12 UTC, merged